- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.dotfiles: ''
    ~/.gitconfig:
    ~/.gitconfig-personal:
    ~/.gitignore_global:
    ~/.bash_aliases:
    ~/.bash_funcs:
    ~/.config/surfingkeys.js:
    ~/.oh-my-zsh: ohmyzsh
    ~/.p10k.zsh:
    ~/.tmux:
    ~/tmux/plugins/tpm: zsh/tpm
    ~/tmux/plugins/tmux-resurrect: zsh/tmux-resurrect
    # tmux source not source
    ~/.tmux.conf.local:
      ignore-missing: true
      path: tmux/.tmux.conf.local
    ~/.tmux.conf:
      ignore-missing: true
      path: tmux/.tmux.conf
    ~/.config/nvim: nvim
    ~/.zshrc:

- shell:
  - git submodule sync --recursive
  # the following have to run after linking ~/.gitconfig
  -
    command: git update-submodules
    stdout: true
    stderr: true
  - ln -fs ./zsh/zsh-syntax-highlighting ./ohmyzsh/plugins/zsh-syntax-highlighting
  - ln -fs ./zsh/zsh-autosuggestions ./ohmyzsh/plugins/zsh-autosuggestions
  - ln -fs ./zsh/history-search-multi-word ./ohmyzsh/plugins/history-search-multi-word
  - ln -fs ./zsh/powerlevel10k ./ohmyzsh/custom/themes/powerlevel10k
