- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.zshrc:
    ~/.tmux.conf.local: .tmux/.tmux.conf.local
    ~/.tmux.conf: .tmux/.tmux.conf
    ~/.config/nvim: nvim
    ~/.gitconfig:
    ~/.gitconfig-personal:
    ~/.bash_aliases:
    ~/.bash_funcs:
    ~/.config/surfingkeys.js:
    ~/.oh-my-zsh: ohmyzsh

- shell:
  - git submodule sync --recursive
  # the following have to run after linking ~/.gitconfig
  - git update-submodules
