- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.dotfiles: ''
    ~/.gitconfig:
      force: true
    ~/.gitconfig-personal:
    ~/.gitignore_global:
    ~/.bash_aliases:
    ~/.bash_funcs:
    ~/.config/surfingkeys.js:
    ~/.oh-my-zsh: ohmyzsh
    ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions: zsh/zsh-autosuggestions
    ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting: zsh/zsh-syntax-highlighting
    ~/.oh-my-zsh/custom/plugins/history-search-multi-word: zsh/history-search-multi-word
    ~/.oh-my-zsh/custom/themes/powerlevel10k: zsh/powerlevel10k
    ~/.p10k.zsh:
    ~/.tmux:
    ~/.tmux/plugins/tpm: zsh/tpm
    ~/.tmux/plugins/tmux-resurrect: zsh/tmux-resurrect
    ~/.tmux/plugins/tmux-continuum: zsh/tmux-continuum
    # tmux source not source
    ~/.tmux.conf.local:
      ignore-missing: true
      path: tmux/.tmux.conf.local
    ~/.tmux.conf:
      ignore-missing: true
      path: tmux/.tmux.conf
    ~/.config/nvim: nvim
    ~/.config/proxy: proxy
    ~/.zshrc:
      force: true

- shell:
  - git submodule sync --recursive
  # the following have to run after linking ~/.gitconfig
  -
    command: git update-submodules
    stdout: true
    stderr: true
